_target_: recs_utils.implicit_model.ImplicitALS
rating_col_name: 'progress'
inner_model:
  _target_: implicit.als.AlternatingLeastSquares
  factors: 64
  use_native: true
  regularization: 0.5
  alpha: 1.0
  iterations: 10
  random_state: 1921239
