_target_: recs_utils.implicit_model.ImplicitRecommenderWithInterConf
rating_col_name: 'progress'
inner_model:
  _target_: implicit.als.AlternatingLeastSquares
  factors: 64
  use_native: true
  regularization: 2.01
  alpha: 1.0
  iterations: 8
  random_state: 1921239
