_target_: recs_utils.hybrid_model.LightFMRecommender
num_epoch: 10
num_threads: 6
progress_column: 'progress'
progress_quant_level: 5
model:
  _target_: lightfm.lightfm.LightFM
  no_components: 32
  k: 5
  n: 10
  learning_schedule: "adagrad"
  loss: "warp"
  learning_rate: 0.13
  rho: 0.95
  epsilon: 1e-6
  item_alpha: 0.0
  user_alpha: 0.0
  max_sampled: 5
  random_state: 23