hydra:
  run:
    dir: ./exp/single
  sweep:
    dir: ./exp/hyperparams_als
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}
  job:
    chdir: true
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1728
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: maximize
    storage: null
    study_name: als
    n_trials: 30
    n_jobs: 1
    params:
      model.inner_model.factors: choice(16, 32, 64)
      model.inner_model.regularization: range(1.0e-2, 10.0)
      model.inner_model.alpha: 1.0
      model.inner_model.iterations: range(5, 10)


defaults:
  - model: als
  - data: mts_lib
  - cv: base
  - override hydra/sweeper: optuna
  - _self_




