hydra:
  run:
    dir: ./exp/single
  sweep:
    dir: ./exp/hyperparams_light_fm
    subdir: ${hydra.job.num}_${hydra.job.override_dirname}
  job:
    chdir: true
  sweeper:
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: 1728
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: maximize
    storage: null
    study_name: lighfm
    n_trials: 30
    params:
      model.model.no_components: choice(16, 32)
      model.model.learning_rate: range(0.05, 0.2, step=0.01)
      model.num_epoch: range(8, 15)

defaults:
  - model: lightfm
  - data: mts_lib
  - cv: base
  - wandb: base
  - _self_
  - override hydra/sweeper: optuna

wandb:
  group: "lightfm-${model.model.loss}-hyperparams-search"
